add_newline = false
format = """
$directory$git_branch$git_status
$character
"""
[directory]
truncation_length = 1
truncate_to_repo = true
style = "bold blue"

[git_branch]
style = "bold blue"

[hostname]
ssh_only = false

[ruby]
disabled = true
